### ISSUE TITLE
pokeget changes ownership of user's home directory to root and does not delete the makefile or license

### ISSUE THREAD

**Issue by everest-linux** [everest-linux/glacier-pkgs#2]

**Comment by everest-linux** [comment]
pretty sure this issue is fixed in the newest version of glacier (0.3rc)

**Comment by talwat** [comment]
Whoops, sorry about that, the LICENSE issue actually has been fixed in the script I use to generate the glacier package, but the Makefile issue still stands.

**Comment by everest-linux** [comment]
definitely fixed in glacier 5.0rc
